### ISSUE TITLE
Update CSIStorageCapacity API Version

### ISSUE THREAD

**Issue by mfroembgen** [jatalocks/kube-arch-scheduler#2]
Please consider updating CSIStorageCapacity API version from **v1beta1** to **v1** to keep compatibility on kubernetes 1.27 and above (https://kubernetes.io/docs/reference/using-api/deprecation-guide/#csistoragecapacity-v127)

**Comment by mfroembgen** [comment]
FYI: That should be resolved by upgrading the go dependencies. (k8s.io/kubernetes)

**Comment by ElementTech** [comment]
Solved by @pl4nty
