### ISSUE TITLE
While I was Trying  run the scheduler locally while connected to your Kubernetes cluster’s context:

### ISSUE THREAD

**Issue by DevOpsFreako** [jatalocks/kube-arch-scheduler#3]
Im Getting Error  

no kind "KubeSchedulerConfiguration" is registered for version "kubescheduler.config.k8s.io/v1" in scheme "pkg/runtime/scheme.go:100"
exit status 1

I have used This Command to change  v1beta3     to  v1    in every file as  v1beta3 decrypted and it will not work  
find . -type f -exec sed -i 's/v1beta3/v1/g' {} +

data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration

Next, I'm running as the root user so I provide the root config file  address 
export KUBECONFIG=/etc/kubernetes/admin.conf

/etc/kubernetes/admin.conf  for client connection 

go run main.go --authentication-kubeconfig /etc/kubernetes/admin.conf --authorization-kubeconfig /etc/kubernetes/admin.conf --config=./example/scheduler-config.yaml --v=2

About my Versioning 

root@k8s-master:~# export PATH=$PATH:/usr/local/go/bin
go version
go version go1.21.4 linux/amd64
root@k8s-master:~# kubectl version --client && docker --version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.8", GitCommit:"66fee42707cd7f5a89f1987f7cb81b02dd19161c", GitTreeState:"clean", BuildDate:"2023-11-15T16:59:43Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Docker version 24.0.7, build afdd53b

@mfroembgen @amitai-devops  @ElementTech 
please look into this issue  and update your repo

**Comment by ElementTech** [comment]
Solved by @pl4nty
